ci:
  # skip any check that needs internet access
  skip: [prettier, eslint, stylelint]

default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        # Version bump conflict with this hook
        exclude: "^package\\.json$"
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: forbid-new-submodules
      - id: check-builtin-literals
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formater.
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: [--max-line-length=200]
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: "(^scripts/bump_version\\.py$)|(^binder/jupyter_config\\.py$)|(/setup\\.py$)"
        args: ["--config-file", "pyproject.toml"]
        additional_dependencies: [tornado, pytest]
        stages: [manual]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
        stages: [manual]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: 'jlpm run prettier'
        language: node
        types_or: [json, ts, tsx, javascript, jsx, css]
      #- id: eslint
      #  name: eslint
      #  entry: 'jlpm run eslint'
      #  language: node
      #  types_or: [ts, tsx, javascript, jsx]
      - id: stylelint
        name: stylelint
        entry: 'jlpm run stylelint'
        language: node
        types: [css]
